import { Poppins } from "next/font/google";
import "./globals.css";
import NavbarFooterWrapper from "@/components/NavbarFooterWrapper";
import { Providers } from "@/providers/Providers";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Artisan Sync",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased min-h-screen flex flex-col bg-[#10101E]`}
      >
        <Providers>
          <NavbarFooterWrapper>{children}</NavbarFooterWrapper>
        </Providers>
      </body>
    </html>
  );
}
